### ISSUE TITLE
Error running test

### ISSUE THREAD

**Issue by ProxyCausal** [timothyrubin/DependencyLDA#1]
Hi, I compiled samplers according to instructions and trained both distributions with success I think (says chains already exist). Then when I try to run the test script I get this:

Error using DependencyLDA Sample TestDocuments (line 112)
Assertion failed.

I assume this has to do with the scripts I ran above not creating all the files but there are some in the dataset folders testing and training output

I want to implement your model on my own data, conceptually it sounds interesting, but I have little matlab or C++ knowlege so I am wondering if it will be hard to port to python and use on my own data? Also, am just wondering how this compare to extreme multilabel classifiers like FastXML.

Thanks

**Comment by ProxyCausal** [comment]
Well, just made chains `files.pwc.resultsfile =  sprintf('%s/AvgPWC_A%02d_B%2.3f_%02dChains.mat'` lowercase. Now I'm getting this error:
```
Undefined function or variable 'GibbsSampler_TagLDA_DCAlpha_V04'.

Error in DependencyLDA_Sample_TestDocuments (line 178)
            [DP Z] = GibbsSampler_TagLDA_DCAlpha_V04(testdata.widx, testdata.wdidx, DC_Alpha, pWC, ITERS_WBURNIN ,
            SEED, OUTPUT); DP=[];
```
Isn't it referencing the compiled C files? Should I just copy it in to the Test folder like the GibbsSamplerLDATAGS3.mexmaci64 file used when training the word distributions? Not really sure how your program works under the hood.

Thanks

**Comment by timothyrubin** [comment]
Hey enmatics--sorry about the delayed response, just realized that my notifications had been going to an old academic email address.  In regards to the two issues you note:

1 - It sounds like you fixed the issue. Just make sure that 'files.pwc.resultsfile' points to the file created by the script 'Compute_GetAvgPWC_New_V01.m' (containing the averaged label-word distributions).

2 - Yeah, this just sounds like an issue with the compiled .mex file not being on your matlab path. You can either copy the compiled file into the working directory you are running 'DependencyLDA_Sample_TestDocuments.m' from, or you can add the '/Mex_Samplers/' directory to your matlab path (so that it knows to look in that directory).

Lastly: that would be great if you could port this to Python! If you're able to get it working I'd be happy to link people to it in the documentation, since I've got a strong preference for python these days. It shouldn't be that hard to port over (although for the compiled code, you'll want to refactor the code to leverage things like vectorized operations in numpy). There's lots of examples of other LDA models implemented in python. This may not be the best example but I'm very familiar with my other repo on a different topic model that's implemented entirely in python here: 

[GC-LDA](https://github.com/timothyrubin/python_gclda)
